#!/bin/sh
##plotwatt
### BEGIN INIT INFO
# Provides:          tkpower-plotwatt
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: tkpower-plotwatt init
# Description:       Starts up tkpower-plotwatt
### END INIT INFO

# Author: Tim Krapil <tim@krapil.com>

case "$1" in
  start)
  exec forever --sourceDir=/home/pi/tkpower/plotwatt -p /var/run start plotwatt.js
  ;;

  stop)
  exec forever stop --sourceDir=/home/pi/tkpower/plotwatt plotwatt.js
  ;;
esac

exit 0

