#!/bin/sh
##collector
### BEGIN INIT INFO
# Provides:          tkpower-collector
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: tkpower-collector init
# Description:       Starts up tkpower-collector
### END INIT INFO

# Author: Tim Krapil <tim@krapil.com>

case "$1" in
  start)
  exec forever --sourceDir=/home/pi/tkpower -p /var/run start collector.js /dev/ttyAMA0
  ;;

  stop)
  exec forever stop --sourceDir=/home/pi/tkpower collector.js
  ;;
esac

exit 0

