#!/bin/sh
##logger
### BEGIN INIT INFO
# Provides:          tkpower-logger
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: tkpower-logger init
# Description:       Starts up tkpower-logger
### END INIT INFO

# Author: Tim Krapil <tim@krapil.com>

case "$1" in
  start)
  exec forever --sourceDir=/home/pi/tkpower -p /var/run start logger.js
  ;;

  stop)
  exec forever stop --sourceDir=/home/pi/tkpower logger.js
  ;;
esac

exit 0

